# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-15 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=30)),
                ('no_of_projects', models.IntegerField(default=0)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
    ]
