# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-15 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='awardss.User'),
            preserve_default=False,
        ),
    ]
