# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-15 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0004_projects_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
