# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0005_auto_20200215_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='id',
        ),
        migrations.AddField(
            model_name='ratings',
            name='project_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='awardss.Projects'),
            preserve_default=False,
        ),
    ]
