# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0006_auto_20200215_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
