# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0008_auto_20200215_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
