# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-16 17:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0009_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
