# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-16 17:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0010_auto_20200216_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
