# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-20 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0012_auto_20200217_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
