# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-20 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardss', '0013_auto_20200220_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.TextField(),
        ),
    ]
